apiVersion: "authentication.istio.io/v1alpha1"
kind: "Policy"  
metadata:
  name: "{{ .Chart.Name }}-auth-policy"
spec:
  targets:
  - name: reviews
  - name: details
  peers:
  - mtls:
  origins:
  - jwt:
      issuer: http://keycloak/auth/realms/istio
      jwksUri: http://keycloak/auth/realms/istio/protocol/openid-connect/certs
  principalBinding: USE_ORIGIN 