apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Values.virtualservice.name }}
spec:
  hosts:
  - "*"
  gateways:
  - {{ .Values.gateway.name }}
  http:
  - match:
    - uri:
        exact: /api
    - uri:
        exact: /swagger-ui.html
    route:
    - destination:
        host: {{ .Chart.Name }}
        port: