apiVersion: v1
appVersion: "1.0"
description: A Helm chart for Kubernetes for deploying productpage and dependent components
name: productpage
version: 0.1.0
keywords:
  - quarkus
home: https://github.com/agilesolutions/charts-istio
sources:
  - https://hub.docker.com/agilesolutions
maintainers:
  - name: rob
    email: robert.rong@agile-solutions.ch
