replicaCount: 1
image:
  repository: agilesolutions/productpage
  tag: latest
  pullPolicy: IfNotPresent
service:
  name: productpage-svc
  type: ClusterIP
  externalPort: 80
  internalPort: 8080
  annotations:
    fabric8.io/expose: "true"
    fabric8.io/ingress.annotations: "kubernetes.io/ingress.class: nginx"
gateway:
  name: productpage-gateway
  externalPort: 80
virtualservice:
  name: productpage-virtualservice
  externalPort: 80
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 400m
    memory: 512Mi
probePath: /actuator/health
livenessProbe:
  initialDelaySeconds: 60
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1
readinessProbe:
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1
terminationGracePeriodSeconds: 10